# Use new container infrastructure to enable caching
sudo: false

# Use OSX to by-pass issue with CouchDB PGP Key on Linux
os: osx

# Generic language, we provide our custom builds
language: generic

# Caching so the next build will be fast too.
cache:
  timeout: 1337
  directories:
  - $HOME/.stack
  - $HOME/.local
  - $HOME/.ghc
  - $TRAVIS_BUILD_DIR/.stack-work

# Only clone the repo's tip
git:
  depth: false

# Setup some global env variables
env:
  global:
  - PATH=$HOME/.local/bin:$PATH           # For binaries installed with stack
  - HOMEBREW_NO_AUTO_UPDATE=1             # Prevent Homebrea from spending 5 minutes upgrading itself
  - HOMEBREW_CACHE=$HOME/.local/Homebrew  # Relocate Homebrew's cache which it can actually be cached

# Define custom set of stages
stages:
- snapshot
- extra-dependencies
- wallet-new-specs

# Install foreign dependencies required by some modules below
before_install:
- brew install rocksdb

# Build snapshot & dependencies in different jobs. This copes with Travis limit of 50 minutes per job.
jobs:
  include:
  # Rebuild only the snapshot. Note that, when triggered, job-concurrency should be limited
  # to 1 and we might have to re-play the build multiple times in case it couldn't build
  # everything in one go.
  # Before kicking this action, it would also be advised to cleanup the entire cache. Note that
  # we have a custom snapshot which contains also all the extra deps for cardano-sl; this way,
  # we only have to build them once.
  - stage: snapshot
    if: commit_message =~ /ci@update lts/
    script:
    - mkdir -p ~/.local/bin
    - travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    - travis_wait 42 stack --no-terminal --install-ghc build --only-snapshot
    - stack --no-terminal install cpphs

  # Rebuild only the extra dependencies; mainly: cardano-sl. This isn't part of the custom
  # snapshot because we likely bumps the git hash reference more often  than other dependencies.
  # Still, we build that as a separate job and only triggers it when appropriated. It's cached
  # otherwise.
  - stage: extra-dependencies
    if: commit_message =~ /ci@update stack.yaml/
    script:
    - travis_wait 42 stack --no-terminal build --fast --only-dependencies

  # Run all tests and upload the result to coveralls.
  - stage: wallet-new-specs
    script:
    # TODO Move it into `snapshot` phase
    - travis_retry wget https://gist.github.com/Anviking/323c184cbb7d16e1d9eed852dd58714c/raw/a895eb8380eaa0a6f83dd5d09f4aff2e066f46e9/shc -O $HOME/.local/bin/shc
    - chmod +x $HOME/.local/bin/shc

    - stack clean
    - travis_wait 42 stack --no-terminal test cardano-sl-wallet-new:test:wallet-new-specs --fast --coverage --ghc-options=-optl-Wl,-dead_strip_dylibs
    - shc cardano-sl-wallet-new wallet-new-specs

after_script:
- stack clean
